### ISSUE TITLE
Einheiten der pyhsikalischen Größen

### ISSUE THREAD

**Issue by nullmightybofo** [Painkilla/VO-370.015-Maschinen-und-Antriebe#13]
Einheiten der Größen in der Formelübersicht sollten eigentlich nicht in eckigen Klammern stehen;
Außerdem soweit mit bekannt auch nicht in wie Variablen in Latex in kursiv gesetzt sein.
Es gibt ein empfehlenswertes Latex-Paket dafür: siunitx, z.B.: ftp://ftp.dante.de/tex-archive/macros/latex/exptl/siunitx/siunitx.pdf

Ist fürs erste aber wohl mal wurscht... just sayin'

**Comment by Painkilla** [comment]
Danke, im nächsten Repo werde ich es versuchen einzubauen.

**Comment by nullmightybofo** [comment]
Lösungsvorschlag in #16
