### ISSUE TITLE
configuring upstream for fork

### ISSUE THREAD

**Issue by nullmightybofo** [Painkilla/VO-370.015-Maschinen-und-Antriebe#15]
Vielleicht hilfreich für die Preambel:
Wie man das Original-Repo als upstream remote zum Fork hinzufügt damit man dort eingebrachte Änderungen in den eigenen Fork pullen kann:

https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/

Vllt. mach ich eine kurze Beschreibung in der Preambel, branch+pull request dazu kommt dann ...

**Comment by Painkilla** [comment]
Glaubst du, dass das funktioniert? Wäre natürlich toll und erspart sicher viel Arbeit. package.tex könnte dann auch synchron gehalten werden. Wie willst du das aber mit den Links in dem Dokument lösen? Jedes verweist ja auf ein anderes repo. Ich könnte mir vorstellen, dass man den Link im conf Ordner hinterlegen, welcher dann beim kompilieren im Dokument ersetzt wird. Wie genau, müsste man sich aber erst ansehen.
Es müsste dann ein blankes Repo geben, von dem dann immer gepullt wird.

**Comment by nullmightybofo** [comment]
Vllt. liegt da ein Missverständnis vor: was ich damit erreichen möcht ist, dass man wenn man das Repo forkt (also zb. user xyz/Maschinen-und-Antriebe) und dann dort was ändert, während im "originalen" Repo Painkilla/Maschinen-und-Antriebe was geändert wird. Dann sollte xyz diese Änderungen auch in seinen Fork übernehmen und dafür richtet er/sie sich als "upstream" das Painkilla-Repo ein. Dann kann er/sie mit z.b. "git fetch upstream master" ansehen was es im Painkilla Repo neues gibt (hier: neue commits auf Painkilla's master branch) und diese nach belieben pullen/mergen.

**Comment by nullmightybofo** [comment]
Was du glaub ich meinst könnte man über ein submodule lösen denke ich. Ein eigenes Repo wo z.B. nur das package.tex drin ist (und alles andere was ausreichend allgemein ist um in allen Repos unverändert benutzt werden zu können). Das kann man dann jeweils als ein repo im repo updaten wenn es Änderungen gibt. Das funktioniert prinzipiells schon.

**Comment by Painkilla** [comment]
aso, ja das habe ich sowieso jetzt machen müssen. submodule verwende ich derzeit schon für die nicht öffentlichen teile, wie z.B. in Edyn oder wellenausbreitung oder den Semester packages. Das mit dem submodule finde ich gut. der /opn/conf/ Ordner wandert nach /conf/ und enthält das submodule, und das Makefile und die README im Hauptordner sind Verknüpfungen auf die neuen Datein.

**Comment by Painkilla** [comment]
ich habe jetzt einen branch erstellt, indem die Konfiguration ausgelagert ist. Bitte bei gelegenheit testen. Zusätzlich habe ich sicherheitshalber noch einen Haftungstext dazugegeben.
